/******************************************************************************

file:         GregexData
author:       Robbert de Groot
copyright:    2011-2011, Robbert de Groot

description:
regex group

******************************************************************************/

/******************************************************************************
include:
******************************************************************************/
#include "pre.h"


// Between zstruct {...} zstruct is autogenerated code.  Touch this code
// and your changes may get lost when the code is regenerated.  Put your
// code outside this block.
// zstruct { ------------------------------------------------------------------
/******************************************************************************
local:
variable:
******************************************************************************/
static Gb _isStarted = gbFALSE; //lint !e956

/******************************************************************************
global:
function:
******************************************************************************/
/******************************************************************************
func: gregexDataCreate
******************************************************************************/
gregexDataAPI_CALL GregexData *gregexDataCreate_(void)
{
   GregexData *regexData;

   genter;

   greturnNullIf(!_isStarted);

   regexData = gmemCreateType(GregexData);
   greturnNullIf(!regexData);

   if (!gregexDataCreateContent(regexData))
   {
      gregexDataDestroy(regexData);
      greturn NULL;
   }

   greturn regexData;
}

/******************************************************************************
func: gregexDataCreateContent
******************************************************************************/
gregexDataAPI_CALL Gb gregexDataCreateContent(GregexData * const regexData)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexData);

   gmemClearType(regexData, GregexData);

   // Init the structure.
   //regexData->groupList           = gregexGroupArrayCreate();
   regexData->rex                 = NULL;
   regexData->string              = gsCreate();
   regexData->stringRex           = gsCreate();

   // Ensure proper initialization.
   greturnFalseIf(!regexData->string);
   greturnFalseIf(!regexData->stringRex);

   greturn gbTRUE;
}

/******************************************************************************
func: gregexDataDestroy
******************************************************************************/
gregexDataAPI_CALL void gregexDataDestroy(GregexData * const regexData)
{
   genter;

   greturnVoidIf(
      !_isStarted ||
      !regexData);

   gregexDataDestroyContent(regexData);

   gmemDestroy(regexData);

   greturn;
}

/******************************************************************************
func: gregexDataDestoryContent
******************************************************************************/
gregexDataAPI_CALL void gregexDataDestroyContent(GregexData const * const regexData)
{
   genter;

   greturnVoidIf(
      !_isStarted ||
      !regexData);

   // Clean up memory.
   //gregexGroupArrayForEach(regexData->groupList, (GrlForEachFunc) gregexGroupDestroy); //lint !e534 !e929 !e960 
   //gregexGroupArrayDestroy(regexData->groupList);
   grexDestroy(regexData->rex);
   gsDestroy(regexData->string);
   gsDestroy(regexData->stringRex);

   greturn;
}

#if 0
/******************************************************************************
func: gregexDataGetGroupList()
******************************************************************************/
gregexDataAPI_CALL GregexGroupArray * gregexDataGetGroupList(GregexData const * const regexData)
{
   genter;

   greturnNullIf(
      !_isStarted ||
      !regexData);

   greturn regexData->groupList;
}
#endif

/******************************************************************************
func: gregexDataGetRex()
******************************************************************************/
gregexDataAPI_CALL Grex * gregexDataGetRex(GregexData const * const regexData)
{
   genter;

   greturnNullIf(
      !_isStarted ||
      !regexData);

   greturn regexData->rex;
}

/******************************************************************************
func: gregexDataGetString()
******************************************************************************/
gregexDataAPI_CALL Gs * gregexDataGetString(GregexData const * const regexData)
{
   genter;

   greturnNullIf(
      !_isStarted ||
      !regexData);

   greturn regexData->string;
}

/******************************************************************************
func: gregexDataGetStringRex()
******************************************************************************/
gregexDataAPI_CALL Gs * gregexDataGetStringRex(GregexData const * const regexData)
{
   genter;

   greturnNullIf(
      !_isStarted ||
      !regexData);

   greturn regexData->stringRex;
}

/******************************************************************************
func: gregexDataIsStarted()
******************************************************************************/
gregexDataAPI_CALL Gb gregexDataIsStarted(void)
{
   genter;

   greturn _isStarted;
}

/******************************************************************************
func: gregexDataSetRex()
******************************************************************************/
gregexDataAPI_CALL Gb gregexDataSetRex(GregexData * const regexData, Grex * const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexData);

   regexData->rex = value;

   greturn gbTRUE;
}

/******************************************************************************
func: gregexDataSetString()
******************************************************************************/
gregexDataAPI_CALL Gb gregexDataSetString(GregexData const * const regexData, Gs const * const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexData);

   greturnFalseIf(!gsSet(regexData->string, value)); //lint !e960 !e9008

   greturn gbTRUE;
}

/******************************************************************************
func: gregexDataSetStringRex()
******************************************************************************/
gregexDataAPI_CALL Gb gregexDataSetStringRex(GregexData const * const regexData, Gs const * const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexData);

   greturnFalseIf(!gsSet(regexData->stringRex, value)); //lint !e960 !e9008

   greturn gbTRUE;
}

/******************************************************************************
func: gregexDataStart
******************************************************************************/
Gb gregexDataStart(void)
{
   genter;

   greturnTrueIf(_isStarted);

   _isStarted = gbTRUE;

   greturn _isStarted;
}

/******************************************************************************
func: gregexDataStop
******************************************************************************/
void gregexDataStop(void)
{
   genter;

   greturnVoidIf(!_isStarted);

   _isStarted = gbFALSE;

   greturn;
}

// } zstruct ------------------------------------------------------------------

/******************************************************************************
local:
constant:
******************************************************************************/



/******************************************************************************
type:
******************************************************************************/
/******************************************************************************
variable:
******************************************************************************/
/******************************************************************************
prototype:
******************************************************************************/
/******************************************************************************
global:
function:
******************************************************************************/
/******************************************************************************
local:
function:
******************************************************************************/

