/******************************************************************************

file:         GregexGroup
author:       Robbert de Groot
copyright:    2011-2011, Robbert de Groot

description:
regex group

******************************************************************************/

/******************************************************************************
include:
******************************************************************************/
#include "pre.h"


// Between zstruct {...} zstruct is autogenerated code.  Touch this code
// and your changes may get lost when the code is regenerated.  Put your
// code outside this block.
// zstruct { ------------------------------------------------------------------
/******************************************************************************
local:
variable:
******************************************************************************/
static Gb _isStarted = gbFALSE; //lint !e956

/******************************************************************************
global:
function:
******************************************************************************/
/******************************************************************************
func: gregexGroupCreate
******************************************************************************/
gregexGroupAPI_CALL GregexGroup *gregexGroupCreate_(void)
{
   GregexGroup *regexGroup;

   genter;

   greturnNullIf(!_isStarted);

   regexGroup = gmemCreateType(GregexGroup);
   greturnNullIf(!regexGroup);

   if (!gregexGroupCreateContent(regexGroup))
   {
      gregexGroupDestroy(regexGroup);
      greturn NULL;
   }

   greturn regexGroup;
}

/******************************************************************************
func: gregexGroupCreateContent
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupCreateContent(GregexGroup * const regexGroup)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   gmemClearType(regexGroup, GregexGroup);

   // Init the structure.
   regexGroup->count               = gregexCharCountONE;
   regexGroup->string              = gsCreate();

   // Ensure proper initialization.
   greturnFalseIf(!regexGroup->string);

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupDestroy
******************************************************************************/
gregexGroupAPI_CALL void gregexGroupDestroy(GregexGroup * const regexGroup)
{
   genter;

   greturnVoidIf(
      !_isStarted ||
      !regexGroup);

   gregexGroupDestroyContent(regexGroup);

   gmemDestroy(regexGroup);

   greturn;
}

/******************************************************************************
func: gregexGroupDestoryContent
******************************************************************************/
gregexGroupAPI_CALL void gregexGroupDestroyContent(GregexGroup const * const regexGroup)
{
   genter;

   greturnVoidIf(
      !_isStarted ||
      !regexGroup);

   // Clean up memory.
   gsDestroy(regexGroup->string);

   greturn;
}

/******************************************************************************
func: gregexGroupGetCount()
******************************************************************************/
gregexGroupAPI_CALL GregexCharCount gregexGroupGetCount(GregexGroup const * const regexGroup)
{
   genter;

   greturnIf(
         !_isStarted ||
         !regexGroup,
      gregexCharCountONE);

   greturn regexGroup->count;
}

/******************************************************************************
func: gregexGroupGetIndexEnd()
******************************************************************************/
gregexGroupAPI_CALL Gindex gregexGroupGetIndexEnd(GregexGroup const * const regexGroup)
{
   genter;

   greturnIf(
         !_isStarted ||
         !regexGroup,
      gindexERROR);

   greturn regexGroup->indexEnd;
}

/******************************************************************************
func: gregexGroupGetIndexStart()
******************************************************************************/
gregexGroupAPI_CALL Gindex gregexGroupGetIndexStart(GregexGroup const * const regexGroup)
{
   genter;

   greturnIf(
         !_isStarted ||
         !regexGroup,
      gindexERROR);

   greturn regexGroup->indexStart;
}

/******************************************************************************
func: gregexGroupGetOperation()
******************************************************************************/
gregexGroupAPI_CALL GregexOp gregexGroupGetOperation(GregexGroup const * const regexGroup)
{
   genter;

   greturnIf(
         !_isStarted ||
         !regexGroup,
      gregexOpNONE);

   greturn regexGroup->operation;
}

/******************************************************************************
func: gregexGroupGetString()
******************************************************************************/
gregexGroupAPI_CALL Gs * gregexGroupGetString(GregexGroup const * const regexGroup)
{
   genter;

   greturnNullIf(
      !_isStarted ||
      !regexGroup);

   greturn regexGroup->string;
}

/******************************************************************************
func: gregexGroupIsNegated()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupIsNegated(GregexGroup const * const regexGroup)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   greturn regexGroup->isNegated;
}

/******************************************************************************
func: gregexGroupIsStarted()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupIsStarted(void)
{
   genter;

   greturn _isStarted;
}

/******************************************************************************
func: gregexGroupSetCount()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupSetCount(GregexGroup * const regexGroup, GregexCharCount const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   regexGroup->count = value;

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupSetIndexEnd()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupSetIndexEnd(GregexGroup * const regexGroup, 
   Gindex const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   regexGroup->indexEnd = value;

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupSetIndexStart()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupSetIndexStart(GregexGroup * const regexGroup, 
   Gindex const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   regexGroup->indexStart = value;

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupSetIsNegated()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupSetIsNegated(GregexGroup * const regexGroup, Gb const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   regexGroup->isNegated = value;

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupSetOperation()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupSetOperation(GregexGroup * const regexGroup, GregexOp const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   regexGroup->operation = value;

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupSetString()
******************************************************************************/
gregexGroupAPI_CALL Gb gregexGroupSetString(GregexGroup const * const regexGroup, Gs const * const value)
{
   genter;

   greturnFalseIf(
      !_isStarted ||
      !regexGroup);

   greturnFalseIf(!gsSet(regexGroup->string, value)); //lint !e960 !e9008

   greturn gbTRUE;
}

/******************************************************************************
func: gregexGroupStart
******************************************************************************/
Gb gregexGroupStart(void)
{
   genter;

   greturnTrueIf(_isStarted);

   _isStarted = gbTRUE;

   greturn _isStarted;
}

/******************************************************************************
func: gregexGroupStop
******************************************************************************/
void gregexGroupStop(void)
{
   genter;

   greturnVoidIf(!_isStarted);

   _isStarted = gbFALSE;

   greturn;
}

// } zstruct ------------------------------------------------------------------

/******************************************************************************
local:
constant:
******************************************************************************/



/******************************************************************************
type:
******************************************************************************/
/******************************************************************************
variable:
******************************************************************************/
/******************************************************************************
prototype:
******************************************************************************/
/******************************************************************************
global:
function:
******************************************************************************/
/******************************************************************************
local:
function:
******************************************************************************/

