/******************************************************************************

file:         GregexGroup
author:       Robbert de Groot
copyright:    2011-2011, Robbert de Groot

description:
regex group

******************************************************************************/

#if !defined(GregexGroup_HEADER)
#define      GregexGroup_HEADER

/******************************************************************************
include:
******************************************************************************/

/*lint -save -e960 */
#define gregexGroupAPI_CALL            grlAPI
#define gregexGroupArrayVECTOR_SIZING  gbTRUE
/*lint -restore */

/*****************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif
/*****************************************************************************/

// Between zstruct {...} zstruct is autogenerated code.  Touch this code
// and your changes may get lost when the code is regenerated.  Put your
// code outside this block.
// zstruct { ------------------------------------------------------------------
/******************************************************************************
type:
******************************************************************************/
typedef struct _GregexGroup GregexGroup;
struct _GregexGroup
{
   GregexCharCount    count;
   Gindex             indexEnd;
   Gindex             indexStart;
   Gb                 isNegated;
   GregexOp           operation;
   Gs                *string;
};

/******************************************************************************
prototype:
******************************************************************************/
//lint -save -e960 -e961 -e9023 -e9024 -e9026
#define gregexGroupCreate() (GregexGroup *) gleakCreate((Gp *) gregexGroupCreate_(), gsizeof(GregexGroup))
/*lint -restore */

gregexGroupAPI_CALL GregexGroup        *gregexGroupCreate_(           void);
gregexGroupAPI_CALL Gb                  gregexGroupCreateContent(     GregexGroup       * const regexGroup);

gregexGroupAPI_CALL void                gregexGroupDestroy(           GregexGroup       * const regexGroup);
gregexGroupAPI_CALL void                gregexGroupDestroyContent(    GregexGroup const * const regexGroup);

gregexGroupAPI_CALL GregexCharCount     gregexGroupGetCount(          GregexGroup const * const regexGroup);
gregexGroupAPI_CALL Gindex              gregexGroupGetIndexEnd(       GregexGroup const * const regexGroup);
gregexGroupAPI_CALL Gindex              gregexGroupGetIndexStart(     GregexGroup const * const regexGroup);
gregexGroupAPI_CALL GregexOp            gregexGroupGetOperation(      GregexGroup const * const regexGroup);
gregexGroupAPI_CALL Gs                 *gregexGroupGetString(         GregexGroup const * const regexGroup);

gregexGroupAPI_CALL Gb                  gregexGroupIsNegated(         GregexGroup const * const regexGroup);

gregexGroupAPI_CALL Gb                  gregexGroupIsStarted(         void);

gregexGroupAPI_CALL Gb                  gregexGroupSetCount(          GregexGroup       * const regexGroup, GregexCharCount const value);
gregexGroupAPI_CALL Gb                  gregexGroupSetIndexEnd(       GregexGroup       * const regexGroup, Gindex const value);
gregexGroupAPI_CALL Gb                  gregexGroupSetIndexStart(     GregexGroup       * const regexGroup, Gindex const value);
gregexGroupAPI_CALL Gb                  gregexGroupSetIsNegated(      GregexGroup       * const regexGroup, Gb const value);
gregexGroupAPI_CALL Gb                  gregexGroupSetOperation(      GregexGroup       * const regexGroup, GregexOp const value);
gregexGroupAPI_CALL Gb                  gregexGroupSetString(         GregexGroup const * const regexGroup, Gs const * const value);

                    Gb                  gregexGroupStart(             void);
                    void                gregexGroupStop(              void);

// } zstruct ------------------------------------------------------------------

/*****************************************************************************/
#ifdef __cplusplus
}
#endif
/*****************************************************************************/

#endif
