/******************************************************************************

file:         GregexData
author:       Robbert de Groot
copyright:    2011-2011, Robbert de Groot

description:
regex group

******************************************************************************/

#if !defined(GregexData_HEADER)
#define      GregexData_HEADER

/******************************************************************************
include:
******************************************************************************/

/*lint -save -e960 */
#define gregexDataAPI_CALL grlAPI
/*lint -restore */

/*****************************************************************************/
#ifdef __cplusplus
extern "C" {
#endif
/*****************************************************************************/

// Between zstruct {...} zstruct is autogenerated code.  Touch this code
// and your changes may get lost when the code is regenerated.  Put your
// code outside this block.
// zstruct { ------------------------------------------------------------------
/******************************************************************************
type:
******************************************************************************/
typedef struct _GregexData GregexData;
struct _GregexData
{
   //GregexGroupArray *            groupList;
   Grex *                      rex;
   Gs *                        string;
   Gs *                        stringRex;
};

/******************************************************************************
prototype:
******************************************************************************/
//lint -save -e960 -e961 -e9023 -e9024 -e9026
#define gregexDataCreate() (GregexData *) gleakCreate((Gp *) gregexDataCreate_(), gsizeof(GregexData))
/*lint -restore */

gregexDataAPI_CALL GregexData          *gregexDataCreate_(           void);
gregexDataAPI_CALL Gb                   gregexDataCreateContent(     GregexData       * const regexData);

gregexDataAPI_CALL void                 gregexDataDestroy(           GregexData       * const regexData);
gregexDataAPI_CALL void                 gregexDataDestroyContent(    GregexData const * const regexData);

//gregexDataAPI_CALL GregexGroupArray  *gregexDataGetGroupList(      GregexData const * const regexData);
gregexDataAPI_CALL Grex                *gregexDataGetRex(            GregexData const * const regexData);
gregexDataAPI_CALL Gs                  *gregexDataGetString(         GregexData const * const regexData);
gregexDataAPI_CALL Gs                  *gregexDataGetStringRex(      GregexData const * const regexData);

gregexDataAPI_CALL Gb                   gregexDataIsStarted(         void);

gregexDataAPI_CALL Gb                   gregexDataSetRex(            GregexData       * const regexData, Grex     * const value);
gregexDataAPI_CALL Gb                   gregexDataSetString(         GregexData const * const regexData, Gs const * const value);
gregexDataAPI_CALL Gb                   gregexDataSetStringRex(      GregexData const * const regexData, Gs const * const value);

                   Gb                   gregexDataStart(             void);
                   void                 gregexDataStop(              void);

// } zstruct ------------------------------------------------------------------

/*****************************************************************************/
#ifdef __cplusplus
}
#endif
/*****************************************************************************/

#endif
